name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.leaked-secrets }}"

  create-release:
    name: Create release
    needs: test-action
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.1.0
        with:
          versionSpec: '6.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4.1.0

      - name: Create Release (tag)
        uses: ncipollo/release-action@v1.20.0
        with:
          allowUpdates: false
          skipIfReleaseExists: true
          draft: false
          makeLatest: true
          tag: v${{ steps.gitversion.outputs.semVer }}
          name: Release v${{ steps.gitversion.outputs.semVer }}
          generateReleaseNotes: true
          body:
            Release ${{ steps.gitversion.outputs.semVer }} of ${{ github.event.repository.name }}

      - name: Create Release (latest)
        uses: ncipollo/release-action@v1.20.0
        with:
          allowUpdates: true
          skipIfReleaseExists: false
          draft: false
          makeLatest: false
          tag: latest
          name: Release v${{ steps.gitversion.outputs.semVer }}
          generateReleaseNotes: true
          body:
            Release ${{ steps.gitversion.outputs.semVer }} of ${{ github.event.repository.name }}
