name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Infisical secrets check (local action)
        id: secrets
        uses: ./
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_COMMENT: false

      - name: Show output
        run: |
          echo "Secrets leaked: ${{ steps.secrets.outputs['secrets-leaked'] }}"
      - name: Validate action result
        run: |
          if [ "${{ steps.secrets.outputs.secrets-leaked }}" != "0" ]; then
            echo "Test failed: action detected secrets"
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint workflow files
        uses: rhysd/actionlint@v1
